name: Update Submodules

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository with submodules
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # Step 2: Update Submodules to Latest Commits
      - name: Update Submodules
        run: |
          git submodule update --remote --recursive
          git status
